---
services:
  sweetaddress-db:
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ${DATABASE_PATH}/${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:/data/db
    networks:
      - app-net

  sweetaddress-backend:
    image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-backend:${CI_COMMIT_BRANCH}
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend
    restart: unless-stopped
    environment:
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      JWT_SECRET: "${JWT_SECRET}"
      MONGODB_URL: "mongodb://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db:27017/${CI_PROJECT_NAME}"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_NAME: "${BOT_NAME}"
      NODE_ENV: "${NODE_ENV}"
      APP_URL: "https://api.${DOMAIN_NAME}"
      SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"
      SENTRY_ENVIRONMENT: "${NODE_ENV}" 

    labels:
      - traefik.enable=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.entrypoints=websecure
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.rule=Host(`api.${DOMAIN_NAME}`)
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.tls=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.tls.certresolver=letsencrypt
      - traefik.http.services.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-backend.loadbalancer.server.port=3002
    depends_on:
      - sweetaddress-db
    networks:
      - traefik
      - app-net

  sweetaddress-frontend:
    image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-frontend:${CI_COMMIT_BRANCH}
    container_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.entrypoints=websecure
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.rule=Host(`app.${DOMAIN_NAME}`)
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.tls=true
      - traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-frontend.loadbalancer.server.port=80
    depends_on:
      - sweetaddress-backend
    networks:
      - traefik

networks:
  traefik:
    external: true
  app-net:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-net
    driver: bridge