FROM node:20.17.0-alpine3.20 AS builder

RUN apk add --no-cache --update \
            python3 \
            make \
            g++ \
            krb5-dev \
            bash && \
    rm -rf /tmp/* /var/tmp/* 

WORKDIR /app

ARG TYPE_SERVER
ENV TYPE_SERVER="$TYPE_SERVER"

COPY package.json yarn.lock ./

COPY $TYPE_SERVER/package.json ./$TYPE_SERVER/

RUN yarn install --frozen-lockfile

COPY $TYPE_SERVER/ ./$TYPE_SERVER/
COPY shared/ ./shared/

RUN cd $TYPE_SERVER && yarn build --mode production

FROM nginx:alpine AS runner

ARG TYPE_SERVER
ENV TYPE_SERVER="$TYPE_SERVER"

COPY --from=builder /app/$TYPE_SERVER/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]